### ISSUE TITLE
Typo in python example

### ISSUE THREAD

**Issue by szreik** [vanandrew/warpkit#10]
Hi! Just wanted to let you know that in your python example for calling medic, I think in line 3 you meant to put:
`from warpkit.utilities import displacement_map_to_field`
instead of:
`from warpkit.utilities import displacement_map_to_warp` 

:)

**Comment by vanandrew** [comment]
Thanks for catching that! As you can tell, I went through several naming iterations before settling on the current function names :)

**Comment by vanandrew** [comment]
Fixed in 94525a5.
