### ISSUE TITLE
Purpose of `check_temporal_consistency_corr`

### ISSUE THREAD

**Issue by tsalo** [vanandrew/warpkit#11]
@vanandrew I'm in the process of translating MEDIC into an SDCFlows workflow, but I'm a little confused about [`check_temporal_consistency_corr`](https://github.com/vanandrew/warpkit/blob/cbd70174fc80bff882a6f59d278f84526f485fb8/warpkit/unwrap.py#L305). Does that function raise an exception if the phase unwrapping solutions aren't temporally consistent, or does it modify `unwrapped_data` in place?

**Comment by vanandrew** [comment]
Hey @tsalo. That function modifies the unwrapped phase data in-place. The main reason is to avoid any memory copies as that function is very memory intensive (it has to keep track of the entire phase dataset which is volume x frames x echos).

**Comment by tsalo** [comment]
Thanks!
