### ISSUE TITLE
:package: Build Docker image and deploy to DockerHub

### ISSUE THREAD

**Issue by tsalo** [vanandrew/warpkit#7]
Given the complicated dependency setup (C++ + Julia + Python + ROMEO) it seems like MEDIC would be useful via Docker.

**Comment by vanandrew** [comment]
Repo now has a CI pipeline to push out pypi and docker releases.

I'd also like to do a conda package, but I'm less familiar with how to make those (See #6), So going to wait for someone to come along to help out with that.

Closing issue.

**Comment by szreik** [comment]
Any chance you could push the docker container to DockerHub?

**Comment by vanandrew** [comment]
It's currently up on [ghcr.io](https://github.com/vanandrew/warpkit/pkgs/container/warpkit), so you can pull it via: `docker pull ghcr.io/vanandrew/warpkit:latest`.

Is there a reason to also have it on DockerHub? I can try and set that up if there's a compelling enough reason for it.

**Comment by szreik** [comment]
Nevermind! I thought it had to be on dockerhub in order to pull it through singularity. It doesn't. For anyone curious you can just pull it with this command: 

`singularity pull docker://ghcr.io/vanandrew/warpkit:latest`

Thank you for the quick response!

**Comment by vanandrew** [comment]
Good to know!

Let me know how it goes with `singularity` (or I guess the replacement `apptainer`). I haven't done much testing with either, so it will be good to get feedback on it.
